config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#about'
  devise_for :users
  mount RailsAdmin::Engine => '/myc-adminit', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'cvms#show'
    resources :cvms
    resources :users, only: [:show]
  get 'about' => 'static_pages#about'
  get 'my_cv' => 'cvms#show'
  get 'contact' => 'static_pages#contact'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cvm.rb
class Cvm < ApplicationRecord

  belongs_to :user

  has_many :educations, :inverse_of => :cvm, dependent: :destroy

  has_many :experiences, :inverse_of => :cvm, dependent: :destroy

  accepts_nested_attributes_for :educations, :experiences, allow_destroy: true

  validates     :fname, :lname, :street, :district,:country, :land,
                 :mobile, :email, :website, :skill, :interest,
                 presence: true

  validates_presence_of :educations, :experiences

end

app/models/education.rb
class Education < ApplicationRecord

  belongs_to :cvm, optional: true

  validates :level, :institute, :year, :percentage,
            presence: true

end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :cvm

  validates :company, :position, :jobdetail, :startdate, presence: true

  has_many  :projects, dependent: :destroy

  accepts_nested_attributes_for :projects, allow_destroy: true


end

app/models/project.rb
class Project < ApplicationRecord

belongs_to :experience, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :cvm

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/datetime.rb
  def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
  end

app/controllers/cvms_controller.rb
class CvmsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cvm=Cvm.new
  end


  def create
    @cvm=Cvm.new(cvm_params)
    @cvm.user=current_user
    if @cvm.save
      flash[:success] = "Your CV has been successfully submitted!"
      redirect_to cvm_path(@cvm)
    else
      flash[:alert] = "Woops! Looks like there has been an error!"
      redirect_to root_path
    end
  end

  def new
    @cvm=Cvm.new
  end

  def show
    if current_user.cvm.nil?
      redirect_to new_cvm_path
    else
    @cvm=current_user.cvm
    respond_to do |format|
      format.html
      format.json
      format.pdf do
      render pdf: "resume_#{@cvm.fname}",
            type: "application/pdf",
            template: "cvms/resume.html.erb",
            disposition: "inline",
            layout: "pdf.html"

          end
       end
    end
  end

  def edit
    @cvm=Cvm.find(params[:id])
  end



  def update
    @cvm=Cvm.find(params[:id])
      if @cvm.update(cvm_params)
        flash[:success] = "CV has been updated!"
        redirect_to cvm_path(@cvm)
      else
        redirect_to edit_cvm_path
      end
  end

  def destroy
    @cvm = Cvm.find(params[:id])
    @cvm.destroy
    flash[:success] = "CV was successfully deleted!"
    redirect_to root_path
  end


  private
    def cvm_params
      params.require(:cvm).permit(:email, :website, :skill, :interest, :fname, :mname, :lname, :street,
                                  :district, :land, :country, :mobile,

                                    educations_attributes: [
                                    :id, :level, :institute, :year, :percentage, :_destroy
                                    ],

                                    experiences_attributes: [
                                    :id, :company, :position, :jobdetail, :startdate, :enddate, :_destroy,

                                    projects_attributes: [
                                    :id, :pname, :description, :startdate, :enddate, :_destroy
                                    ]

                                    ]
                                    )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def about
end

def contact
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvms_helper.rb
module CvmsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cvms/_education_fields.html.erb
<div class="nested-fields">
  <div class="left-col2">
    <b>Level *</b>
    <%= f.input :level, label:false, :input_html => {:style=> 'width: 80px'}, placeholder: "Level" %>
  </div>
  <div class="center-col1">
    <b>Institute *</b>
    <%= f.input :institute, label:false, :input_html => {:style=> 'width: 270px'},  placeholder: "ABC Institute" %>
  </div>
  <div class="center-col2">
    <b>Completed Year *</b>
    <%= f.input :year, :as => :string, label:false, :input_html => {:style=> 'width: 270px' , 'data-provide': 'datepicker' }, placeholder: "Month-Date-Year" %>
  </div>
  <div class="right-col2">
    <b>Percentage/GPA *</b>
    <%= f.input :percentage, label:false, :input_html => {:style=> 'width: 280px'},placeholder: "78 or 3.5 " %>
  </div>
  <%= link_to_remove_association 'Remove Education Detail', f, class: 'btn btn-danger btn-xs' %>
</div>

app/views/cvms/_experience_fields.html.erb
<div class="nested-fields">
  <h4><b>Company Info</b></h4>
  <div class="left-col2">
    <b>Name *</b>
    <%= f.input :company, label:false, :input_html => {:style=> 'width: 80px'}, placeholder: "XYZ" %>
  </div>
  <div class="right-col4">
    <b>Position *</b>
    <%= f.input :position, label:false, :input_html => {:style=> 'width: 220px'}, placeholder: "Branch Manager" %>
  </div>
  <div class="center-col3">
    <b>Job Description *</b>
    <%= f.input :jobdetail, label:false, :input_html => {:style=> 'width: 320px'},  placeholder: "Worked as Branch Manager in Banepa" %>
  </div>
  <div class="center-col4">
    <b>From *</b>
    <%= f.input :startdate, as: :string, label:false, :input_html => {:style=> 'width: 120px' , 'data-provide': 'datepicker'}, placeholder: "02/12/2015" %>
  </div>
  <div class="work-end-date">
    <div class="right-col3">
      <b>To </b>
      <%= f.input :enddate, as: :string, label:false, :input_html => {:style=> 'width: 120px' , 'data-provide': 'datepicker'},placeholder: "07/06/2017" %>
    </div>
  </div>
  <br><br><br><br><br>
  <input type="checkbox" class="work-checkbox"/> I am currently working here.
  <br><br>
  <%= link_to_remove_association 'Remove Company', f, class: 'btn btn-danger btn-xs' %>
  <br><br>
  <%= f.simple_fields_for :projects do |project| %>
  <%= render 'project_fields', :f =>project %>
  <%end%>
  <div class="links">
    <%= link_to_add_association 'Add Projects', f, :projects, class: 'btn btn-primary btn-xs'%>
  </div>
  <hr>
  <script>
  $('.work-checkbox').change(function(){
  var workEndDateDiv = $(this).parent().find('.work-end-date');
  if (this.checked) {
  workEndDateDiv.fadeOut('slow');
  } else {
  workEndDateDiv.fadeIn('slow');
  }
  });
  </script>
</div>

app/views/cvms/_form.html.erb
<h2><center><u>CV Details</u></center></h2>
<%= simple_form_for @cvm do |f| %>
<p>
  <h3><b>Name:</b></h3>
  <div class="left-col">
    <b>First *</b>
    <%= f.input :fname, label: false, :input_html => {:style=> 'width: 300px'}, placeholder: "Rajan" %>
  </div>
  <div class="center-col">
    <b>Middle </b>
    <%= f.input :mname, label: false,:input_html => {:style=> 'width: 300px'}, placeholder: "Prasad" %>
  </div>
  <div class="right-col">
    <b>Last *</b>
    <%= f.input :lname, label: false,:input_html => {:style=> 'width: 300px'}, placeholder: "Bhattarai"%>
  </div>
</p>
<br><br><br>
<p>
  <h3><b>Address: </b></h3>
  <div class="left-col">
    <b>Street *</b>
    <%= f.input :street, label:false, :input_html => {:style=> 'width: 300px'},placeholder: "Patan Dhoka" %>
  </div>
  <div class="center-col">
    <b>District *</b>
    <%= f.input :district, label:false, :input_html => {:style=> 'width: 300px'}, placeholder: "Lalitpur" %>
  </div>
  <div class="right-col">
    <b>Country *</b>
    <%= f.input :country, label:false, :input_html => {:style=> 'width: 300px'}, placeholder: "Country", selected: 'Nepal' %>
  </div>
</p>
<br><br><br>
<p>
  <h3><b>Phone: </b></h3>
  <div class="left-col1">
    <b>Landline *</b>
    <%= f.input :land, label:false, :input_html => {:style=> 'width: 465px'}, placeholder: "01-XXXXXXX"%>
  </div>
  <div class="right-col1">
    <b>Mobile *</b>
    <%= f.input :mobile,  label:false, :input_html => {:style=> 'width: 465px'}, placeholder: "+97798 / 98XXXXXXXX" %>
  </div>
</p>
<br><br><br>
<p>
  <div class="left-col1">
    <b>Email *</b>
    <%= f.input :email, label:false, :input_html => {:style=> 'width: 465px'}, placeholder: "john@example.com" %>
  </div>
  <div class="right-col1">
    <b>Website   *</b>
    <%= f.input :website, label:false, :input_html => {:style=> 'width: 465px'}, placeholder: "example.com" %>
  </div>
</p>
<br><br><br>
<p>
  <h3><b>Education: </b></h3>
  <center><h4><b>Click on Add Education button to add your education details.</b></h4></center>
  <h5><b>At least one record is required!</b></h5>
  <hr>
  <%= f.simple_fields_for :educations do |education| %>
  <%= render 'education_fields', :f=>education %>
  <% end %>
  <div class='links'>
    <br>
    <%= link_to_add_association 'Add Education', f, :educations, class: 'btn btn-primary'%>
  </div>
</p>
<br>
<p>
  <h3><b>Skill *</b></h3>
  <div id="newel1">
    <div class="skill">
      <%= f.input :skill, label: false, input_html: { maxlength: 100 }, placeholder: "Web Developement/Operation Management/Web-Design etc.."%>
    </div>
  </div>
</p>
<br>
<p>
  <h3><b>Experience: </b></h3>
  <center><h4><b>Click on Add Experience button to add your experience details.</b></h4></center>
  <h5><b>At least one company info is required!</b></h5>
  <hr>
  <%= f.simple_fields_for :experiences do |experience| %>
  <%= render 'experience_fields', :f=>experience %>
  <% end %>
  <div class='links'>
    <br>
    <%= link_to_add_association 'Add Experience', f, :experiences, class: 'btn btn-primary'%>
  </div>
</p>
<br>
<p>
  <h3><b>Interest *</b></h3>
  <div id="newel3">
    <div class="interest">
      <%= f.input :interest, label: false, input_html: { maxlength: 100 }, placeholder: "Enter the area of interest. It may be things like technology or tools you are interested to work with." %>
    </div>
  </div>
</p>
<br>
<p>
  <%= f.submit "Submit", class: 'btn btn-primary' %>
</p>
<% end %>

app/views/cvms/_project_fields.html.erb
<div class="nested-fields">
  <h4><b>Project</b></h4>
  <div class="left-col3">
    <b>Project Title </b>
    <%= f.input :pname, label:false, :input_html => {:style=> 'width: 320px'}, placeholder: "CV Management" %>
  </div>
  <div class="center-col3">
    <b>Description</b>
    <%= f.input :description, label:false, :input_html => {:style=> 'width: 320px'},  placeholder: "A project on managing CV for users" %>
  </div>
  <div class="center-col4">
    <b>Start Date </b>
    <%= f.input :startdate, label:false, :input_html => {:style=> 'width: 120px', 'data-provide': 'datepicker'}, placeholder: "01/01/2015" %>
  </div>
  <div class="project-end-date">
    <div class="right-col3">
      <b>End Date </b>
      <%= f.input :enddate, label:false, :input_html => {:style=> 'width: 120px', 'data-provide': 'datepicker'},placeholder: "01/01/2016" %>
    </div>
  </div>
  <br><br><br><br><br>
  <input type="checkbox" class="project-checkbox"/> This is ongoing project.
  <br><br>
  <%= link_to_remove_association 'Remove Project', f, class: 'btn btn-danger btn-xs' %><br><br>
  <script>
  $('.project-checkbox').change(function(){
  var projectEndDateDiv = $(this).parent().find('.project-end-date');
  if (this.checked) {
  projectEndDateDiv.fadeOut('slow');
  } else {
  projectEndDateDiv.fadeIn('slow');
  }
  });
  </script>
</div>

app/views/cvms/edit.html.erb
<center><h1>make-your-cv!</h1></center>
<hr/><br>
<h3><u>Please edit your details.</u></h3>
<%= render 'form' %>

app/views/cvms/index.html.erb
<center><h1>make-your-cv</h1></center>
<hr/><br>
<h4><u>Please fill your details! Fields with * are compulsory.</u></h4>
<br>
<%= render 'form' %>

app/views/cvms/new.html.erb
<center><h1>make-your-cv</h1></center>
<hr/><br>
<h4><u>Please fill your details! Fields with * are compulsory.</u></h4>
<br>
<%= render 'form' %>

app/views/cvms/resume.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <blockquote>
            <div id="page-wrap">
                <div id="contact-info" class="vcard">
                    <h2 style="font-size: 48px"><%= "#{@cvm.fname.capitalize} #{@cvm.mname.capitalize} #{@cvm.lname.capitalize}" %></h2>
                    <hr>
                    <p>
                        Cell: <span class="tel"></span><%= "#{@cvm.mobile}" %><br />
                        Adress:</b> <%= "#{@cvm.street.capitalize}, #{@cvm.district.capitalize}, #{@cvm.country.capitalize}" %>
                    </p>
                    Email: <a class="email" href="<%= "mailto://#{@cvm.email}" %>"><%= "#{@cvm.email}" %></a>
                    <br>
                    Website: <a href="<%= "https://#{@cvm.website}" %>"><%= "https://#{@cvm.website}" %></a>
                    <hr>
                    <div class="clear"></div>
                    <dd class="clear"></dd>
                    <dt>Education</dt>
                    <dd>
                    <%@cvm.educations.each do |education| %>
                    <h2><%= education.level.upcase%> </h2>
                    <p><%= education.institute %>, <%= education.year %>, <%= education.percentage %>%</p>
                    <% end %>
                    </dd>
                    <dl>
                        <dd class="clear"></dd>
                        <dt>Skill</dt>
                        <dd>
                        <p><%= @cvm.skill %></p>
                        </dd>
                        <dd class="clear"></dd>
                        <dt>Experience</dt>
                        <dd>
                        <% @cvm.experiences.each do |exp| %>
                        <h2><%= exp.position.capitalize %> at <%= exp.company%></h2>
                        <p>
                            <%= exp.jobdetail %>
                        </p>
                        <p>
                            <%= exp.startdate %>-
                            <%= exp.enddate %>
                        </p>
                        <h2>Project</h2>
                        <hr>
                        <% exp.projects.each do |pro| %>
                        <h4><%= pro.pname %></h4>
                        <p><%= pro.description%></p>
                        <p><%= pro.startdate%>-<%= pro.enddate%></p>
                        <% end %>
                        <br><br>
                        <% end %>
                        </dd>
                        <dd class="clear"></dd>
                        <dt>Interest</dt>
                        <dd><%= @cvm.interest%></dd>
                    </dl>
                </div>
            </div>
        </blockquote>
        <br>
        <br>
        <br>
        <p>
            <center>PDF generated by make-your-cv! <%= Date.today.year %>. </center>
        </p>
    </div>
</div>

app/views/cvms/show-old.html.erb
<center>
<h1>CV Details!</h1>
</center>
<div class="panel panel-default">
    <div class="panel-body">
        <blockquote>
            <h3><b>Name:</b> <%= "#{@cvm.fname} #{@cvm.mname} #{@cvm.lname}" %></h3>
            <h3><b>Adress:</b> <%= "#{@cvm.street}, #{@cvm.district}, #{@cvm.country}" %></h3>
            <h3><b>Phone:</b> <%= "Landline: #{@cvm.land}, Mobile: #{@cvm.mobile}" %></h3>
            <h3><b>Email:</b> <%= @cvm.email %></h3>
            <h3><b>Website:</b> <%= "https://#{@cvm.website}" %></h3>
            <h3><b>Education:</b><br></h3>
            <h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Level</th>
                        <th>Institute</th>
                        <th>Year</th>
                        <th>Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    <%@cvm.educations.each do |education| %>
                    <tr>
                        <td><%= education.level%></td>
                        <td><%= education.institute %></td>
                        <td><%= education.year %></td>
                        <td><%= education.percentage %></td>
                    </tr>
                    <%end %>
                </tbody>
            </table>
            <br>
            </h4>
            <h3><b>Experience: </b></h3>
            <h4>
            <table class="table table-striped">
                <% @cvm.experiences.each do |exp| %>
                <thead>
                    <tr>
                        <th>Company</th>
                        <th>Position</th>
                        <th>Detail</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= exp.company%></td>
                        <td><%= exp.position %></td>
                        <td><%= exp.jobdetail %></td>
                        <td><%= exp.startdate %></td>
                        <td><%= exp.enddate %></td>
                    </tr>
                </tbody>
                <% exp.projects.each do |pro| %>
                <thead>
                    <tr>
                        <th>Project Name</th>
                        <th>Description</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= pro.pname %></td>
                        <td><%= pro.description%></td>
                        <td><%= pro.startdate%></td>
                        <td><%= pro.enddate%></td>
                    </tr>
                </tbody>
                <% end %>
                <% end %>
            </table>
            </h4>
            <h3><b>Skill:</b> <%= @cvm.skill %></h3>
            <h3><b>Interest:</b> <%= @cvm.interest %></h3>
        </blockquote>
        <br>
        <%= link_to "Edit Details", edit_cvm_path(@cvm), class: 'btn btn-primary'%>
        <%= link_to "Delete this record", cvm_path(@cvm), method: :delete, class: 'btn btn-danger'%>
    </div>
</div>
<center>
<%= link_to "Download CV in PDF format", cvm_path(@cvm, format: "pdf"), class: 'btn btn-primary'%>
</center>
<br>
<br>
<br>

app/views/cvms/show.html.erb
<center>
<h1>My CV!</h1>
</center>
<div class="panel panel-default">
    <div class="panel-body">
        <blockquote>
            <div id="page-wrap">
                <div id="contact-info" class="vcard">
                    <h2 style="font-size: 48px"><%= "#{@cvm.fname.capitalize} #{@cvm.mname.capitalize} #{@cvm.lname.capitalize}" %></h2>
                    <hr>
                    <p>
                        Cell: <span class="tel"></span><%= "#{@cvm.mobile}" %><br />
                        Adress:</b> <%= "#{@cvm.street.capitalize}, #{@cvm.district.capitalize}, #{@cvm.country.capitalize}" %>
                    </p>
                    Email: <a class="email" href="<%= "mailto://#{@cvm.email}" %>"><%= "#{@cvm.email}" %></a>
                    <br>
                    Website: <a href="<%= "https://#{@cvm.website}" %>"><%= "https://#{@cvm.website}" %></a>
                    <hr>
                    <div class="clear"></div>
                    <dd class="clear"></dd>
                    <dt>Education</dt>
                    <dd>
                    <%@cvm.educations.each do |education| %>
                    <h2><%= education.level.upcase%> </h2>
                    <p><%= education.institute %>, <%= education.year %>, <%= education.percentage %>%</p>
                    <% end %>
                    </dd>
                    <dl>
                        <dd class="clear"></dd>
                        <dt>Skill</dt>
                        <dd>
                        <p><%= @cvm.skill %></p>
                        </dd>
                        <dd class="clear"></dd>
                        <dt>Experience</dt>
                        <dd>
                        <% @cvm.experiences.each do |exp| %>
                        <h2><%= exp.position.capitalize %> at <%= exp.company%></h2>
                        <p>
                            <%= exp.jobdetail %>
                        </p>
                        <p>
                            <%= exp.startdate %>-
                            <%= exp.enddate %>
                        </p>
                        <h2>Project</h2>
                        <hr>
                        <% exp.projects.each do |pro| %>
                        <h4><%= pro.pname %></h4>
                        <p><%= pro.description%></p>
                        <p><%= pro.startdate%>-<%= pro.enddate%></p>
                        <% end %>
                        <br><br>
                        <% end %>
                        </dd>
                        <dd class="clear"></dd>
                        <dt>Interest</dt>
                        <dd><%= @cvm.interest%></dd>
                    </dl>
                </div>
            </div>
        </blockquote>
        <br>
        <br>
        <br>
        <p>
            <center>PDF generated by make-your-cv! <%= Date.today.year %>. </center>
        </p>
    </div>
</div>
<%= link_to "Edit Details", edit_cvm_path(@cvm), class: 'btn btn-primary'%>
<%= link_to "Delete this record", cvm_path(@cvm), method: :delete, class: 'btn btn-danger'%>
<center>
<%= link_to "Download CV in PDF format", cvm_path(@cvm, format: "pdf"), class: 'btn btn-primary'%>
</center>
<br>
<br>
<br>

app/views/layouts/_admi.html.erb
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Admin</button>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="myModalLabel" style="color:black">If you have been supplied admin-url, enter here!</h4>
            </div>
            <div class="modal-body">
                <script>
                function process() {
                var url = "/" + document.getElementById("url").value;
                location.href = url;
                return false;
                }
                </script>

                <form onSubmit="return process();">
                    <p style="color:black"> URL:
                        <input type="text" name="url" id="url" style="color:black">
                        <input type="submit" value="Admin Dashboard" style="color:black">
                    </p>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_nsignin.html.erb
<% if user_signed_in? %>
  <!-- <li>
    <%= link_to 'Make new CV', new_cvm_path %>
  </li> -->
  <li>
    <%= link_to 'CV', my_cv_path %>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Option
      <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to 'About', about_path %>
      </li>
      <li>
        <%= link_to 'Contact', contact_path %>
      </li>
      <li>
        <%= link_to 'Settings', edit_user_registration_path %>
      </li>
    </ul>
  </li>
  <li>
    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
  </li>
<% end %>

app/views/layouts/_nsignup.html.erb
<% if !user_signed_in? %>
<li>
  <%= link_to 'Login', new_user_session_path %>
</li>
<li>
  <%= link_to 'Signup', new_user_registration_path %>
</li>
<!-- <li>
  <%= link_to 'About', about_path %>
</li>
 --><li>
  <%= link_to 'Contact', contact_path %>
</li>
<% end %>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CV</title>
    <%= wicked_pdf_stylesheet_link_tag "application" -%>
  </head>
  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>